version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: antontut
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  wp:
    build: .
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: antontut