version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
#      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password # any random string will do
      MYSQL_DATABASE: antontut # the name of your mysql database
      MYSQL_USER: user # the name of the database user
      MYSQL_PASSWORD: password
  wp:
    build: .
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: antontut